version: '3.8'

services:

  postgres:
    image: postgres:17.4
    container_name: project-management-db
    restart: always
    environment:
      - POSTGRES_USER: admin
      - POSTGRES_PASSWORD: secret
      - POSTGRES_DB: pmdatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

